version: '3.8'

services:
  redis-database:
    image: redis
    container_name: host_node_normalizer_db
    ports:
      - "6379:6379"
    command:
      ['redis-server','--appendonly', 'yes']
    volumes:
      - redis_data:/data

  api-container:
    container_name: build_node_normalizer
    build:
      context: ..
      dockerfile: redis_and_api_combined/build.Dockerfile
    ports:
      - "8080:8080"
      - "2434:2434"
    tty: true
    volumes:
      - ../comps:/app/NodeNormalization/comps
      - ../confs:/app/NodeNormalization/confs
    depends_on:
      - redis-database

volumes:
  redis_data:
